repos:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        args: [--load-plugins, pylint_flask, pylint_sqlalchemy]
        additional_dependencies: [pylint-flask, pylint-sqlalchemy, pytest]
