services:
  db-dev:
    restart: always
    image: postgres:15.1
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    expose:
      - "5432"
    networks:
      - back-tier
    env_file:
      - ./db.env
  app-dev:
    restart: always
    build: 
      context: .
      target: nlpapp-dev
      dockerfile: ./docker/python/Dockerfile
    command: python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask --debug --app nlp4all run --host=0.0.0.0 --port=5000
    volumes:
      - static_volume_dev:/home/app/nlp4all/static
      - ./nlp4all:/home/app/nlp4all
    ports:
      - "5000:5000"
      - "5678:5678"
    env_file:
      - ./db.dev.env
      - ./app.dev.env
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db-dev
networks:
  front-tier: {}
  back-tier: {}
volumes:
  postgres_data_dev:
  static_volume_dev: