services:
  db-dev:
    restart: always
    image: postgres:15.2
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - back-tier
    env_file:
      - ./db.dev.env
  document-store-dev:
    restart: always
    image: mongo:5.0.15
    ports:
      - "27017:27017"
    networks:
      - back-tier
    volumes:
      - mongo_data_dev:/data/db
    env_file:
      - ./db.dev.env
  rabbitmq-dev:
    restart: always
    image: rabbitmq:3.11
    expose:
      - "5672"
    networks:
      - back-tier
  app-dev:
    restart: always
    build: 
      context: .
      target: nlpapp-dev
      dockerfile: ./docker/python/Dockerfile
    command: ./run-nlp4all.sh
    volumes:
      - ./nlp4all:/home/app/nlp4all
    ports:
      - "5000:5000"
      - "5678:5678"
    env_file: # variables defined here cannot be referenced in compose.yml
      - ./db.dev.env
      - ./app.dev.env
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db-dev
      - worker-dev
      - document-store-dev
  worker-dev:
    restart: always
    build: 
      context: .
      target: nlpapp-dev
      dockerfile: ./docker/python/Dockerfile
    command: bash -c "watchmedo auto-restart --recursive --pattern='*.py' -- celery -A make_celery worker -l info"
    volumes:
      - ./nlp4all:/home/app/nlp4all
    env_file:
      - ./db.dev.env
      - ./app.dev.env
    networks:
      - back-tier
    depends_on:
      - db-dev
      - rabbitmq-dev
      - document-store-dev
networks:
  front-tier: {}
  back-tier: {}
volumes:
  postgres_data_dev:
  mongo_data_dev:
